apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swapi-app
  template:
    metadata:
      labels:
        app: swapi-app
    spec:
      containers:
      - name: swapi-uservice
        image: swapi-uservice:latest
        imagePullPolicy: Never   # set this policy to use local images to load them to Minikube & deploy
        ports:
        - containerPort: 8000