apiVersion: v1
kind: Service
metadata:
  name: swapi-service
spec:
  type: NodePort
  selector:
    app: swapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
